version: 1
script:
  # Remove any previous build
  - rm -rf AppDir  | true
  # Make src dirs
  - mkdir -p AppDir/usr/src
  # Make icons dirs
  - mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps/
  # Copy the icon to icons dir
  - cp ./icons/plethysmo_256.png AppDir/usr/share/icons/hicolor/256x256/apps/plethysmo.png
  # Make bin dirs
  - mkdir -p AppDir/usr/bin
  # Install application dependencies
  - python3 -m pip install --ignore-installed --prefix=/usr --root=AppDir ../..

AppDir:
  path: ./AppDir

  app_info:
    id: https://github.com/ILLGrenoble/plethysmo
    name: plethysmo
    icon: plethysmo
    version: 0.0.0
    # Set the python executable as entry point
    exec: usr/bin/python3
    # Set the application main script path as argument. Use '$@' to forward CLI parameters
    exec_args: "$APPDIR/usr/bin/plethysmo"

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'

    include:
      - python3
    exclude: []

  runtime:
    version: "continuous"
    env:
      PATH: '${APPDIR}/usr/bin:${PATH}'
      # Set python home
      # See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME
      PYTHONHOME: '${APPDIR}/usr'
      # Path to the site-packages dir or other modules dirs
      # See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH
      PYTHONPATH: '${APPDIR}/usr/lib/python3.8/site-packages'

AppImage:
  update-information: 'gh-releases-zsync|AppImageCrafters|python-appimage-example|latest|python-appimage-*x86_64.AppImage.zsync'
  sign-key: None
  arch: x86_64
